trigger:
  batch: true
  branches:
    include:
      - "*"

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/heads/master
    endpoint: GitHub (SFA)

stages:
- stage: Build
  jobs:
  - template: pipeline-templates/job/code-build.yml

- template: azure-pipelines-templates/deploy/stage/nuget-publish.yml@das-platform-building-blocks
    