jobs:
- job: CodeBuild
  pool:
      name: DAS - Continuous Integration Agents
      demands: LATEST_DOTNET_VERSION -equals 3.1
  variables:
  - group: BUILD Management Resources
  steps:
    - template: azure-pipelines-templates/build/step/gitversion.yml@das-platform-building-blocks
    
    - template: azure-pipelines-templates/build/step/nuget-pack.yml@das-platform-building-blocks
      parameters:
        DotNetStandardPackagesToPack: |
          src/working/templatepack.csproj
